#ifndef PAYMENT_GATEWAY_LLD_ENUMS_RETRYSTRATEGYTYPE_H
#define PAYMENT_GATEWAY_LLD_ENUMS_RETRYSTRATEGYTYPE_H

namespace payment_gateway_lld {
enum class RetryStrategyType { LINEAR, EXPONENTIAL_BACKOFF };
}

#endif
