#ifndef OTP_GENERATION_SYSTEM_LLD_ENUMS_OTPPURPOSE_H
#define OTP_GENERATION_SYSTEM_LLD_ENUMS_OTPPURPOSE_H

namespace otp_lld {

enum class OTPPurpose { LOGIN, SIGNUP, PAYMENT, PASSWORD_RESET };

} // namespace otp_lld

#endif // OTP_GENERATION_SYSTEM_LLD_ENUMS_OTPPURPOSE_H
