#ifndef OTP_GENERATION_SYSTEM_LLD_ENUMS_OTPSTATUS_H
#define OTP_GENERATION_SYSTEM_LLD_ENUMS_OTPSTATUS_H

namespace otp_lld {

enum class OTPStatus { PENDING, VERIFIED, EXPIRED, LOCKED };

} // namespace otp_lld

#endif // OTP_GENERATION_SYSTEM_LLD_ENUMS_OTPSTATUS_H
